"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ShieldCheck, UserPlus } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Row={user_id:string;display_name:string;support_role:string;active:boolean;availability_status:string;admin_role:string;ai_view:boolean;ai_test:boolean;ai_suggest:boolean;ai_edit:boolean;ai_approve:boolean;ai_behavior:boolean};

export function SupportAdminManagement({initialAdmins}:{initialAdmins:Row[]}){
  const supabase=useMemo(()=>createClient(),[]);const router=useRouter();const [email,setEmail]=useState("");const [name,setName]=useState("");const [role,setRole]=useState("agent");const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [message,setMessage]=useState<string|null>(null);
  async function add(){if(!email.trim()||!name.trim())return;setBusy(true);setError(null);const {error:e}=await supabase.rpc("support_add_admin_by_email",{p_email:email.trim(),p_display_name:name.trim(),p_support_role:role});if(e)setError(e.message);else{setEmail("");setName("");setMessage("Support administrator added. MFA is required before privileged support access.");router.refresh()}setBusy(false)}
  async function setActive(id:string,active:boolean){setBusy(true);const {error:e}=await supabase.rpc("support_set_admin_active",{p_user_id:id,p_active:active});if(e)setError(e.message);else router.refresh();setBusy(false)}
  async function setPerm(a:Row,key:keyof Pick<Row,"ai_view"|"ai_test"|"ai_suggest"|"ai_edit"|"ai_approve"|"ai_behavior">){const next={...a,[key]:!a[key]};setBusy(true);const {error:e}=await supabase.rpc("support_set_admin_ai_permissions",{p_user_id:a.user_id,p_view:next.ai_view,p_test:next.ai_test,p_suggest:next.ai_suggest,p_edit:next.ai_edit,p_approve:next.ai_approve,p_behavior:next.ai_behavior});if(e)setError(e.message);else router.refresh();setBusy(false)}
  return <section className="support-panel-card" style={{marginTop:16}}><h3><ShieldCheck/> Multiple support administrators</h3><p>Owner-only. Add an existing Rewear account as an Admin or Support Agent. Support Agents can suggest AI corrections but cannot publish official AI policy unless you explicitly grant approval permission.</p><div className="support-search-row" style={{gridTemplateColumns:"1.3fr 1fr 160px auto"}}><input className="support-control-input" placeholder="Existing account email" value={email} onChange={e=>setEmail(e.target.value)}/><input className="support-control-input" placeholder="Display name" value={name} onChange={e=>setName(e.target.value)}/><select className="support-control-select" value={role} onChange={e=>setRole(e.target.value)}><option value="agent">Support Agent</option><option value="admin">Admin</option></select><button className="support-primary-btn" type="button" disabled={busy||!email.trim()||!name.trim()} onClick={()=>void add()}><UserPlus/> Add</button></div>{message?<p style={{color:"#166534"}}>{message}</p>:null}{error?<div className="support-admin-error">{error}</div>:null}<div className="support-kb-list" style={{maxHeight:"none",marginTop:14}}>{initialAdmins.map(a=><div className="support-kb-item" key={a.user_id}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center"}}><div><b>{a.display_name}</b><p>{a.admin_role} · Support role {a.support_role} · {a.availability_status} · {a.active?"Active":"Disabled"}</p></div>{a.admin_role!=="owner"?<button className={a.active?"support-danger-btn":"support-secondary-btn"} type="button" disabled={busy} onClick={()=>void setActive(a.user_id,!a.active)}>{a.active?"Disable":"Enable"}</button>:<span className="support-admin-chip">Owner</span>}</div>{a.admin_role!=="owner"?<div className="support-channel-grid" style={{marginTop:8}}>{([['ai_view','AI view'],['ai_test','Test Bot'],['ai_suggest','Suggest training'],['ai_edit','Edit training'],['ai_approve','Approve training'],['ai_behavior','Behavior rules']] as const).map(([key,label])=><label key={key}><input type="checkbox" checked={a[key]} disabled={busy} onChange={()=>void setPerm(a,key)}/>{label}</label>)}</div>:null}</div>)}</div></section>
}
