"use client";

import { useMemo, useState } from "react";
import { Bell, BellRing, Clock3, Mail, MessageSquareMore, Smartphone, Wifi } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Preferences={admin_id?:string;dashboard_enabled:boolean;push_enabled:boolean;email_enabled:boolean;sms_enabled:boolean;whatsapp_enabled:boolean;telegram_enabled:boolean;event_preferences:Record<string,boolean>};
type Hour={day_of_week:number;enabled:boolean;opens_at:string|null;closes_at:string|null;timezone:string};
const days=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
const eventOptions=[
  ["human.requested","Customer requests a human"],["ai.handoff","AI cannot safely answer"],["customer.reply","Customer replies to an admin"],
  ["conversation.assigned","Conversation assigned to me"],["conversation.reopened","Conversation reopened"],["ai.training_needed","AI training needed"]
] as const;

export function SupportSettingsClient({userId,displayName,initialAvailability,initialPreferences,initialHours}:{userId:string;displayName:string;initialAvailability:string;initialPreferences:Preferences|null;initialHours:Hour[]}){
  const supabase=useMemo(()=>createClient(),[]);
  const [availability,setAvailability]=useState(initialAvailability||"offline");
  const [prefs,setPrefs]=useState<Preferences>(initialPreferences||{dashboard_enabled:true,push_enabled:true,email_enabled:false,sms_enabled:false,whatsapp_enabled:false,telegram_enabled:false,event_preferences:{}});
  const [hours,setHours]=useState<Hour[]>(initialHours.map(h=>({...h,opens_at:h.opens_at?.slice(0,5)||null,closes_at:h.closes_at?.slice(0,5)||null})));
  const [permission,setPermission]=useState<NotificationPermission|"unsupported">(()=>typeof window!=="undefined"&&"Notification" in window?Notification.permission:"unsupported");
  const [busy,setBusy]=useState(false);const [message,setMessage]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);

  async function updateAvailability(value:string){setBusy(true);setError(null);const {error:e}=await supabase.rpc("support_set_availability",{p_status:value});if(e)setError(e.message);else{setAvailability(value);setMessage(`Availability updated to ${value}.`)}setBusy(false)}
  async function savePrefs(next=prefs){setBusy(true);setError(null);const payload={admin_id:userId,dashboard_enabled:next.dashboard_enabled,push_enabled:next.push_enabled,email_enabled:next.email_enabled,sms_enabled:next.sms_enabled,whatsapp_enabled:next.whatsapp_enabled,telegram_enabled:next.telegram_enabled,event_preferences:next.event_preferences,updated_at:new Date().toISOString()};const {error:e}=await supabase.from("admin_notification_preferences").upsert(payload,{onConflict:"admin_id"});if(e)setError(e.message);else{setPrefs(next);setMessage("Notification preferences saved.")}setBusy(false)}
  async function enableBrowserNotifications(){if(!("Notification" in window)||!("serviceWorker" in navigator)){setPermission("unsupported");return}try{await navigator.serviceWorker.register("/admin-sw.js",{scope:"/"});const result=await Notification.requestPermission();setPermission(result);if(result==="granted"){const next={...prefs,push_enabled:true};await savePrefs(next)}}catch{setPermission("unsupported")}}
  function toggleChannel(key:keyof Preferences){const next={...prefs,[key]:!prefs[key]};setPrefs(next);void savePrefs(next)}
  function toggleEvent(key:string){const next={...prefs,event_preferences:{...prefs.event_preferences,[key]:!(prefs.event_preferences?.[key]??true)}};setPrefs(next);void savePrefs(next)}
  function updateHour(day:number,patch:Partial<Hour>){setHours(v=>v.map(h=>h.day_of_week===day?{...h,...patch}:h))}
  async function saveHours(){setBusy(true);setError(null);for(const h of hours){const {error:e}=await supabase.rpc("support_update_business_hour",{p_day:h.day_of_week,p_enabled:h.enabled,p_opens:h.enabled?h.opens_at:null,p_closes:h.enabled?h.closes_at:null,p_timezone:h.timezone||"America/Toronto"});if(e){setError(`${days[h.day_of_week]}: ${e.message}`);setBusy(false);return}}setMessage("Support business hours saved.");setBusy(false)}

  return <div className="support-settings-grid">
    <div className="support-side">
      <section className="support-panel-card"><h3>Admin availability</h3><p>{displayName}, choose whether customers should be told that live support is currently available.</p><div className="support-button-row">{["online","busy","offline"].map(s=><button key={s} type="button" className={availability===s?"support-primary-btn":"support-secondary-btn"} disabled={busy} onClick={()=>void updateAvailability(s)}>{s==="online"?<Wifi/>:s==="busy"?<Clock3/>:<Smartphone/>} {s[0].toUpperCase()+s.slice(1)}</button>)}</div></section>
      <section className="support-panel-card"><h3>Notification channels</h3><p>Preferences are stored per administrator. Dashboard notifications are live now. Browser notifications work while the Admin/PWA session is active; background push requires secure provider/VAPID secret configuration.</p><div className="support-channel-grid"><label><input type="checkbox" checked={prefs.dashboard_enabled} onChange={()=>toggleChannel("dashboard_enabled")}/><Bell/> Dashboard</label><label><input type="checkbox" checked={prefs.push_enabled} onChange={()=>toggleChannel("push_enabled")}/><BellRing/> Web Push / PWA</label><label><input type="checkbox" checked={prefs.email_enabled} onChange={()=>toggleChannel("email_enabled")}/><Mail/> Email fallback</label><label><input type="checkbox" checked={prefs.sms_enabled} onChange={()=>toggleChannel("sms_enabled")}/><Smartphone/> SMS optional</label><label><input type="checkbox" checked={prefs.whatsapp_enabled} onChange={()=>toggleChannel("whatsapp_enabled")}/><MessageSquareMore/> WhatsApp later</label><label><input type="checkbox" checked={prefs.telegram_enabled} onChange={()=>toggleChannel("telegram_enabled")}/><MessageSquareMore/> Telegram later</label></div><div style={{marginTop:12}}>{permission==="granted"?<span className="support-admin-chip"><BellRing/> Browser notifications allowed on this device</span>:permission==="denied"?<p>Browser notifications are blocked. Enable them in this site’s browser settings.</p>:permission==="unsupported"?<p>This browser does not expose notification permission here.</p>:<button className="support-primary-btn" type="button" onClick={()=>void enableBrowserNotifications()}><Bell/> Enable notifications on this device</button>}</div></section>
      <section className="support-panel-card"><h3>Notify me for</h3><div className="support-channel-grid">{eventOptions.map(([key,label])=><label key={key}><input type="checkbox" checked={prefs.event_preferences?.[key]??true} onChange={()=>toggleEvent(key)}/>{label}</label>)}</div></section>
    </div>

    <section className="support-panel-card"><h3>Business hours</h3><p>These hours are configurable and use the selected timezone. No fake/default opening hours are imposed.</p>{hours.map(h=><div className="support-day-row" key={h.day_of_week}><b>{days[h.day_of_week]}</b><label><input type="checkbox" checked={h.enabled} onChange={e=>updateHour(h.day_of_week,{enabled:e.target.checked})}/> Open</label><input className="support-control-input" type="time" value={h.opens_at||"09:00"} disabled={!h.enabled} onChange={e=>updateHour(h.day_of_week,{opens_at:e.target.value})}/><input className="support-control-input" type="time" value={h.closes_at||"17:00"} disabled={!h.enabled} onChange={e=>updateHour(h.day_of_week,{closes_at:e.target.value})}/></div>)}<label style={{display:"flex",flexDirection:"column",gap:5,marginTop:12,fontSize:12,fontWeight:750}}>Timezone<select className="support-control-select" value={hours[0]?.timezone||"America/Toronto"} onChange={e=>setHours(v=>v.map(h=>({...h,timezone:e.target.value})))}><option value="America/Toronto">America/Toronto</option><option value="America/Montreal">America/Montreal</option></select></label><button className="support-primary-btn" style={{marginTop:12}} type="button" disabled={busy} onClick={()=>void saveHours()}>Save business hours</button>{message?<p style={{color:"#166534"}}>{message}</p>:null}{error?<div className="support-admin-error">{error}</div>:null}</section>
  </div>
}
