import Link from 'next/link';
import {requireAdmin} from '@/lib/admin-auth';
import {loadPilot} from '@/lib/pilot';
import {CATALOG_CATEGORIES} from '@/lib/catalog-taxonomy';
import {savePilot,logWork,resolveQuestion} from './actions';
import '../settings/settings.css';
export const dynamic='force-dynamic';
export default async function PilotPage({searchParams}:{searchParams:Promise<{message?:string}>}){
 const {supabase,access}=await requireAdmin();
 const [pilot,params,items,logs,questions]=await Promise.all([loadPilot(),searchParams,supabase.from('items').select('id,name,status,final_seller_earnings_cents,sold_price_cents'),supabase.from('pilot_work_logs').select('item_id,minutes,cost_cents,task,created_at').order('created_at',{ascending:false}),supabase.from('product_questions').select('id,item_id,email,question,status,created_at').eq('status','new').order('created_at',{ascending:false}).limit(100)]);
 const inventory=items.data??[];const work=logs.data??[];const minutes=work.reduce((n,r)=>n+r.minutes,0);const sold=inventory.filter(i=>i.status==='sold');const costs=work.reduce((n,r)=>n+r.cost_cents,0);const margin=sold.reduce((n,i)=>n+(i.sold_price_cents??0)-(i.final_seller_earnings_cents??0),0)-costs;
 const editable=access.can_manage_selling_rules&&access.has_aal2;
 return <main className="admin-settings-shell"><section className="admin-settings-wrap"><Link href="/admin">← Admin</Link><h1>Pilot Settings</h1><p>Pause categories without deleting products, inspection workflows or account history. Disable pilot mode to restore all categories and pickup days.</p>{params.message&&<p role="status">{params.message}</p>}
 <form action={savePilot} className="selling-rules-form"><fieldset disabled={!editable}><section className="settings-card"><label className="settings-check"><input type="checkbox" name="enabled" defaultChecked={pilot.enabled}/>Pilot mode</label><h2>Active categories</h2>{CATALOG_CATEGORIES.map(c=><label className="settings-check" key={c.value}><input type="checkbox" name="categories" value={c.value} defaultChecked={pilot.categories.includes(c.value)}/>{c.label}</label>)}<div className="settings-grid three"><label>Maximum inventory items<input name="cap" type="number" min="1" max="10000" defaultValue={pilot.item_cap} required/></label><label>Duration (weeks)<input name="weeks" type="number" min="6" max="8" defaultValue={pilot.duration_weeks} required/></label><label>Start date (optional)<input name="start" type="date" defaultValue={pilot.started_at?.slice(0,10)??''}/></label></div><h2>Pickup days · Montréal time</h2>{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((d,i)=><label className="settings-check" key={d}><input type="checkbox" name="days" value={i} defaultChecked={pilot.pickup_days.includes(i)}/>{d}</label>)}<p>Only existing available slots on selected days can be booked. Existing bookings are preserved. Turning off pilot mode does not enable payments or external services.</p><button className="save-rules">Save settings</button></section></fieldset></form>
 <section className="settings-card"><h2>Pilot measurements</h2><p>{inventory.length} items · {sold.length} sold · Sell-through: {inventory.length?Math.round(sold.length/inventory.length*100):0}%</p><p>Logged work: {(minutes/60).toFixed(2)} hours · Average: {inventory.length?(minutes/60/inventory.length).toFixed(2):'0'} hours/item.</p><p>Recorded contribution before unlogged costs: ${(margin/100).toFixed(2)} CAD.</p><p>This is not verified net profit. Record labour cost, collection, packaging, fees and returns as actual costs. No go/no-go decision is made automatically.</p>{items.error||logs.error?<p>Some metrics could not be loaded.</p>:null}</section>
 <form action={logWork} className="settings-card"><h2>Log actual item work</h2><fieldset disabled={!editable}><label>Item<select name="item" required>{inventory.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label><div className="settings-grid three"><label>Minutes<input name="minutes" type="number" min="0" max="1440" required/></label><label>Actual cost CAD (include labour where applicable)<input name="cost" type="number" min="0" step="0.01" defaultValue="0" required/></label><label>Work / cost description<input name="task" minLength={3} maxLength={300} required/></label></div><button className="save-rules">Save work entry</button></fieldset></form>
 <section className="settings-card"><h2>Recent work entries</h2>{work.slice(0,50).map((r,i)=><p key={i}>{inventory.find(x=>x.id===r.item_id)?.name}: {r.task} · {r.minutes} min · ${(r.cost_cents/100).toFixed(2)}</p>)}</section>
 <section className="settings-card"><h2>Guest product questions</h2><p>Private staff inbox. Reply using your approved support channel; no email is sent automatically.</p>{questions.error?<p>Inbox unavailable.</p>:questions.data?.length?questions.data.map(q=><article key={q.id}><Link href={'/item/'+q.item_id}>View item</Link><p>{q.question}</p><p>{q.email}</p><form action={resolveQuestion}><input type="hidden" name="id" value={q.id}/><button disabled={!editable}>Mark resolved</button></form></article>):<p>No unanswered product questions.</p>}</section>
 </section></main>;
}
