import test from "node:test";import assert from "node:assert/strict";import { readFile } from "node:fs/promises";import { isCanadianPostal,normalizeCanadianPostal,shippingMessage } from "../lib/shipping.ts";
const sql=await readFile(new URL("../supabase/migrations/20260922093000_configurable_canada_shipping.sql",import.meta.url),"utf8");
test("Canadian postal codes normalize and validate",()=>{assert.equal(normalizeCanadianPostal("h2x 1y4"),"H2X1Y4");assert.equal(isCanadianPostal("H2X 1Y4"),true);assert.equal(isCanadianPostal("D2X 1Y4"),false);assert.equal(isCanadianPostal("90210"),false);});
test("customer messages expose only final result",()=>{assert.equal(shippingMessage({status:"local_free",shippingCents:0}),"Free local delivery");assert.equal(shippingMessage({status:"ok",shippingCents:1895}),"Shipping: $18.95");assert.equal(shippingMessage({status:"local_only"}),"This item is available for local delivery only.");});
test("shipping authority is server-side and checkout snapshots rule version",()=>{assert.match(sql,/private\.shipping_calc\(item_ids,postal_code,null\)/i);assert.match(sql,/shipping_cents,total_cents[\s\S]*subtotal,shipping,subtotal\+shipping/i);assert.match(sql,/order_shipping_snapshots/i);assert.match(sql,/rule_version/i);assert.match(sql,/enable row level security/i);assert.match(sql,/revoke all on public\.shipping_settings/i);});
test("cart packaging does not simply sum individual quotes",()=>{assert.match(sql,/compatibilityGroup/i);assert.match(sql,/package_count/i);assert.match(sql,/ships_separately/i);assert.match(sql,/dimensionalWeightGrams/i);});
test("shipping failure cannot silently become zero",()=>{assert.match(sql,/status','configuration_error'/i);assert.match(sql,/status' not in \('ok','local_free'\)/i);assert.match(sql,/Shipping is currently unavailable to this postal code/i);});

test("existing 20 km shipping foundation is extended rather than duplicated",()=>{assert.match(sql,/alter table public\.shipping_settings add column/i);assert.match(sql,/singleton=true/i);assert.match(sql,/assert_admin_permission\('shipping'\)/i);});
test("customer cannot submit authoritative shipping internals",()=>{assert.match(sql,/private\.shipping_calc\(item_ids,postal_code,null\)/i);for(const forbidden of ["browser_shipping","client_weight","client_zone","client_surcharge"])assert.doesNotMatch(sql,new RegExp(forbidden,"i"));});
test("quotes expire and checkout always recalculates",()=>{assert.match(sql,/expires_at/i);assert.match(sql,/quote_ttl_seconds/i);assert.match(sql,/ship:=private\.shipping_calc\(item_ids,postal_code,null\)/i);});
test("admin configuration is MFA/permission protected",()=>{assert.match(sql,/assert_admin_permission\('shipping'\)/i);assert.match(sql,/revoke all on public\.shipping_zones/i);});
