"use server";
import { revalidatePath } from "next/cache"; import { redirect } from "next/navigation"; import { createClient } from "@/lib/supabase/server";
async function admin(){const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)redirect("/login");const {data:ctx}=await db.rpc("admin_access_context");const access=Array.isArray(ctx)?ctx[0]:ctx;if(!access?.can_manage_shipping||!access?.has_aal2)redirect("/admin/security");return db;}
const txt=(f:FormData,k:string)=>String(f.get(k)??"").trim();const cents=(v:string)=>v===""?null:Math.round(Number(v)*100);const integer=(v:string)=>v===""?null:Math.round(Number(v));function done(m:string){revalidatePath("/admin/shipping");redirect("/admin/shipping?message="+encodeURIComponent(m));}
export async function saveShippingSettings(f:FormData){const db=await admin();const {error}=await db.rpc("admin_update_shipping_engine_settings",{p:{canada_wide_enabled:f.get("canada_wide_enabled")==="on",free_local_enabled:f.get("free_local_enabled")==="on",dimensional_divisor:integer(txt(f,"dimensional_divisor")),handling_cents:cents(txt(f,"handling")),minimum_cents:cents(txt(f,"minimum")),maximum_cents:cents(txt(f,"maximum")),heavy_threshold_grams:Math.round(Number(txt(f,"heavy_threshold_kg"))*1000),heavy_surcharge_cents:cents(txt(f,"heavy_surcharge")),oversize_surcharge_cents:cents(txt(f,"oversize_surcharge")),fragile_surcharge_cents:cents(txt(f,"fragile_surcharge")),quote_ttl_seconds:integer(txt(f,"quote_ttl_seconds"))}});done(error?.message??"Shipping settings saved.");}
export async function saveZone(f:FormData){const db=await admin();const {error}=await db.rpc("admin_upsert_shipping_zone",{p:{id:txt(f,"id")||null,name:txt(f,"name"),base_cents:cents(txt(f,"base")),additional_kg_cents:cents(txt(f,"per_kg")),enabled:f.get("enabled")==="on",priority:integer(txt(f,"priority"))}});done(error?.message??"Shipping zone saved.");}
export async function savePostalRule(f:FormData){const db=await admin();const {error}=await db.rpc("admin_upsert_shipping_postal_rule",{p:{id:txt(f,"id")||null,zone_id:txt(f,"zone_id")||null,fsa_prefix:txt(f,"fsa"),is_local_free:f.get("local")==="on",shipping_disabled:f.get("disabled")==="on",active:f.get("active")==="on",priority:integer(txt(f,"priority"))}});done(error?.message??"Postal/FSA rule saved.");}
export async function saveProfile(f:FormData){const db=await admin();const {error}=await db.rpc("admin_upsert_shipping_profile",{p:{id:txt(f,"id")||null,name:txt(f,"name"),weight_grams:Math.round(Number(txt(f,"weight"))*1000),length_mm:Math.round(Number(txt(f,"length"))*10),width_mm:Math.round(Number(txt(f,"width"))*10),height_mm:Math.round(Number(txt(f,"height"))*10),fragile:f.get("fragile")==="on",oversize:f.get("oversize")==="on",ships_separately:f.get("separate")==="on",local_delivery_only:f.get("local_only")==="on",compatibility_group:txt(f,"compatibility_group"),active:f.get("active")==="on"}});done(error?.message??"Shipping profile saved.");}
export async function saveCategoryRule(f:FormData){const db=await admin();const {error}=await db.rpc("admin_upsert_shipping_category_rule",{p:{id:txt(f,"id")||null,category:txt(f,"category"),subcategory:txt(f,"subcategory")||null,profile_id:txt(f,"profile_id"),surcharge_cents:cents(txt(f,"surcharge")),active:f.get("active")==="on",priority:integer(txt(f,"priority"))}});done(error?.message??"Category shipping rule saved.");}
export async function saveItemShipping(f:FormData){const db=await admin();const num=(k:string,m=1)=>txt(f,k)?Math.round(Number(txt(f,k))*m):null;const {error}=await db.rpc("admin_set_item_shipping",{p_item:txt(f,"item_id"),p_weight_grams:num("weight",1000),p_length_mm:num("length",10),p_width_mm:num("width",10),p_height_mm:num("height",10),p_fragile:f.get("fragile")==="on",p_oversize:f.get("oversize")==="on",p_separate:f.get("separate")==="on",p_local_only:f.get("local_only")==="on",p_profile:txt(f,"profile_id")||null});revalidatePath("/admin/items");if(error)redirect("/admin/items?type=error&message="+encodeURIComponent(error.message));redirect("/admin/items?message="+encodeURIComponent("Item shipping settings saved."));}