"use client";
import { useState } from "react";
import { CheckCircle2, CircleDollarSign, Clock3, CreditCard, Gavel, HeartHandshake, LockKeyhole, Package, Plus, RotateCcw, Shirt, ShoppingBag, Truck, Wallet } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle,DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Tabs,TabsContent,TabsList,TabsTrigger } from "@/components/ui/tabs";

const items=[{name:"Levi’s 501 jeans",status:"Listed",price:"$48.00"},{name:"Aritzia wool coat",status:"Inspection",price:"—"},{name:"Nike Air Max",status:"Sold",price:"$62.00"},{name:"Apple iPhone 14",status:"Testing",price:"—"}];

export function Dashboard({name}:{name:string}){
  const [sent,setSent]=useState<string|null>(null);
  function submit(kind:string){setSent(`${kind} request created. The $20 authorization will be released after the required handoff is completed.`)}
  return <div className="dashboard">
    <section className="welcome"><div><p className="eyebrow dark">Customer dashboard</p><h1>Welcome, {name}.</h1><p>See your balance, follow every item and let us arrange the next collection.</p></div><div className="dash-actions"><RequestDialog label="Request a Bag" icon={<Package/>} onSubmit={()=>submit("Bag")}/><RequestDialog label="Request pickup" icon={<Truck/>} onSubmit={()=>submit("Pickup")}/></div></section>
    {sent&&<div className="success-banner"><CheckCircle2/>{sent}<button onClick={()=>setSent(null)}>×</button></div>}
    <section className="stats"><article className="balance-stat"><div><Wallet/><span>Available balance</span></div><strong>$62.00</strong><small>Use it to shop now or request payout later</small><Button size="sm"><ShoppingBag/> Shop with balance</Button></article><article><div><Shirt/><span>Items with us</span></div><strong>4</strong><small>Fashion and electronics</small></article><article><div><CircleDollarSign/><span>Total earned</span></div><strong>$124.50</strong><small>Since joining</small></article></section>
    <section className="account-panel"><Tabs defaultValue="items"><TabsList><TabsTrigger value="items">My items</TabsTrigger><TabsTrigger value="requests">My requests</TabsTrigger><TabsTrigger value="payout">Payout</TabsTrigger></TabsList><TabsContent value="items"><div className="panel-title"><div><h2>Items we’re handling for you</h2><p>Follow each item from collection and inspection through listing, sale and payout.</p></div><Button variant="outline"><Plus/> Arrange another collection</Button></div><div className="item-table"><div className="table-head"><span>Item</span><span>Status</span><span>Sale value</span></div>{items.map(x=><div className="table-row" key={x.name}><span>{x.name}</span><span><i className={`status ${x.status.toLowerCase()}`}/>{x.status}</span><strong>{x.price}</strong></div>)}</div></TabsContent><TabsContent value="requests"><div className="empty-box"><Package/><h2>No open requests</h2><p>Order a Bag or let us arrange a pickup when your eligible clothing totals at least $100.</p></div></TabsContent><TabsContent value="payout"><div className="payout-box"><Wallet/><div><h2>$62.00 available</h2><p>Add payout details to withdraw your balance.</p></div><Button>Set up payout</Button></div></TabsContent></Tabs></section>
    <section className="consignment-status"><div><Clock3/><span><b>Selling period</b><small>42 days remaining</small></span></div><div className="period-track"><i/></div><div className="end-choice"><b>Unsold item preference</b><button><HeartHandshake/> Donate</button><button><Gavel/> Auction</button><button><RotateCcw/> Return to me</button></div></section>
    <section className="mini-rules"><b>Quick check before sending</b><span>✓ Each clothing piece has $10+ resale value</span><span>✓ Clothing total is $100+</span><span>✓ Washed and neatly folded</span><span>✓ No stains, tears or damage</span></section>
  </div>
}

function RequestDialog({label,icon,onSubmit}:{label:string;icon:React.ReactNode;onSubmit:()=>void}){
  const [open,setOpen]=useState(false);
  const [category,setCategory]=useState<"clothing"|"electronics">("clothing");
  const isBag=label.includes("Bag");
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant={isBag?"default":"outline"}>{icon}{label}</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>{label}</DialogTitle><DialogDescription>Choose what you want us to collect. We’ll show only the terms that apply.</DialogDescription></DialogHeader><form className="request-form" onSubmit={e=>{e.preventDefault();onSubmit();setOpen(false)}}><label>What are we collecting?<select value={category} onChange={e=>setCategory(e.target.value as "clothing"|"electronics")}><option value="clothing">Clothing, shoes or accessories</option><option value="electronics">Electronics</option></select></label><div className="hold-card"><LockKeyhole/><div><b>$20 temporary authorization</b><p>This is not a charge. It is released after we receive and inspect your items. All intake steps are free.</p></div></div><label>Address<Input required placeholder="Street address, city, postal code"/></label><label>Estimated total resale value<Input required type="number" min="100" placeholder="$100 minimum"/></label><div className="terms-box"><b>Required terms for {category}</b>{category==="clothing"?<><p>• Eligible clothing must total at least $100 and each piece should be worth at least $10.</p><p>• Items must be washed, folded and free of stains, tears, holes or missing parts.</p><p>• Accepted clothing is listed for up to 90 days. Unsold items may be donated, auctioned or returned according to your choice.</p></>:<><p>• Devices must power on, function properly and be free of serious physical damage.</p><p>• You must verify ownership. We may check identification, serial numbers or IMEI.</p><p>• Passwords, user accounts and activation locks must be removed before collection.</p><p>• Our technicians test the device and Rewear determines its resale value.</p></>}<p>• Pickup dates are determined and confirmed by Rewear.</p><p>• Company share: 55% up to $100; 50% from $101–$199; 40% from $200–$499; 30% from $500+.</p><p>• Orders over $50 receive free delivery. Under $50: paid shipping or free delivery on our announced schedule.</p></div><label className="check"><input required type="checkbox"/> I confirm my {category} meets the condition, ownership and minimum-value requirements shown above.</label><label className="check"><input required type="checkbox"/> I have read and accept the applicable selling term, commission rates, pickup scheduling and delivery policy.</label><label className="check"><input required type="checkbox"/> I authorize a temporary $20 card hold that will be released after Rewear receives and inspects my items.</label><Button type="submit"><CreditCard/> Accept terms and continue</Button><small className="payment-note">Card details are handled securely by the connected payment provider.</small></form></DialogContent></Dialog>
}
