import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { siteConfig } from "@/lib/site-config";

export const metadata: Metadata = { title: "Terms of Use | Rewear", description: "Terms governing use of the Rewear marketplace." };

export default function TermsPage() {
  return <main className="shipping-policy-page"><header className="policy-header"><Link href="/" className="brand">REWEAR<span>.</span></Link><Link href="/account">My account</Link></header><article className="legal-policy">
    <div className="policy-hero"><p className="eyebrow dark">Terms / Conditions</p><h1>Terms of Use · Conditions d’utilisation</h1><p>Effective September 25, 2026 · En vigueur le 25 septembre 2026</p></div>
    <section lang="fr"><h2>Français</h2><p>En utilisant {siteConfig.businessName}, vous acceptez les présentes conditions ainsi que les politiques applicables affichées au moment de votre opération. Aucune disposition ne limite les droits impératifs prévus par les lois de protection du consommateur applicables.</p><h3>Comptes</h3><p>Vous devez fournir des renseignements exacts, protéger vos identifiants et nous aviser rapidement d’un accès non autorisé. Nous pouvons limiter une activité qui présente un risque de fraude, de sécurité ou d’abus.</p><h3>Catalogue et disponibilité</h3><p>Les articles sont d’occasion et peuvent présenter des signes d’usage décrits dans leur fiche. Une commande n’est pas garantie tant que l’inventaire, le prix, la livraison, les taxes applicables et le paiement n’ont pas été confirmés par nos systèmes. Un article peut être réservé temporairement pendant le paiement.</p><h3>Prix et paiement</h3><p>Les prix sont en dollars canadiens sauf indication contraire. Avant toute transaction payante, le total, les frais, les taxes applicables, la livraison et les modalités pertinentes doivent être présentés avant la confirmation finale. Les données de carte ne doivent être traitées que par le fournisseur de paiement sécurisé activé pour le site.</p><h3>Livraison, retours et remboursements</h3><p>Les conditions affichées dans la politique de livraison et la politique de retours font partie des présentes conditions. Les droits prévus par la loi continuent de s’appliquer.</p><h3>Contenu et conduite</h3><p>Il est interdit de tenter de contourner la sécurité, d’accéder au compte d’autrui, d’automatiser des abus, de soumettre du contenu illégal ou de perturber le service.</p></section>
    <section lang="en"><h2>English</h2><p>By using {siteConfig.businessName}, you agree to these terms and the applicable policies shown at the time of a transaction. Nothing in these terms limits mandatory rights under applicable consumer-protection law.</p><h3>Accounts</h3><p>You must provide accurate information, protect your credentials and promptly report unauthorized access. We may restrict activity that presents a fraud, security or abuse risk.</p><h3>Catalog and availability</h3><p>Items are second-hand and may show signs of use described in their listing. An order is not guaranteed until inventory, price, delivery, applicable taxes and payment are confirmed by our systems. Inventory may be temporarily reserved during checkout.</p><h3>Prices and payment</h3><p>Prices are in Canadian dollars unless stated otherwise. Before any paid transaction, the total, fees, applicable taxes, delivery and relevant terms must be displayed before final confirmation. Card data must be handled only by the secure payment provider enabled for the site.</p><h3>Delivery, returns and refunds</h3><p>The Shipping Policy and Return & Refund Policy form part of these terms. Statutory consumer rights continue to apply.</p><h3>Content and conduct</h3><p>You may not bypass security, access another person’s account, automate abusive activity, submit unlawful content or interfere with the service.</p></section>
    <section><h2>Contact · Coordonnées</h2><p>{siteConfig.businessName}{siteConfig.supportEmail ? <><br/><a href={`mailto:${siteConfig.supportEmail}`}>{siteConfig.supportEmail}</a></> : null}{siteConfig.businessAddress ? <><br/>{siteConfig.businessAddress}</> : null}{siteConfig.businessPhone ? <><br/>{siteConfig.businessPhone}</> : null}</p></section>
    <Link className="policy-back" href="/"><ArrowLeft/> Back to Rewear</Link>
  </article></main>;
}
