import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { siteConfig } from "@/lib/site-config";

export const metadata: Metadata = { title: "Seller Terms | Rewear", description: "Seller and consignment terms for Rewear." };

export default function SellerTermsPage() {
  return <main className="shipping-policy-page"><header className="policy-header"><Link href="/" className="brand">REWEAR<span>.</span></Link><Link href="/account">My account</Link></header><article className="legal-policy">
    <div className="policy-hero"><p className="eyebrow dark">Selling / Vente</p><h1>Seller Terms · Conditions pour vendeurs</h1><p>Effective September 25, 2026 · En vigueur le 25 septembre 2026</p></div>
    <section lang="fr"><h2>Français</h2><p>Ces conditions s’appliquent lorsqu’un vendeur confie des articles à {siteConfig.businessName} pour évaluation, mise en vente et vente selon les règles affichées dans le compte vendeur.</p><h3>Propriété et authenticité</h3><p>Le vendeur confirme qu’il est propriétaire des articles ou autorisé à les vendre, qu’ils ne sont pas volés ou contrefaits et que les renseignements fournis sont exacts. Les articles interdits, dangereux ou non admissibles peuvent être refusés.</p><h3>Évaluation et prix</h3><p>Les articles sont inspectés avant publication. Le prix proposé doit être approuvé selon le flux prévu dans le compte. La tranche de commission du vendeur est verrouillée à partir du prix initial approuvé et ne change pas uniquement parce qu’un article est ensuite réduit; le montant en dollars peut toutefois varier selon le prix de vente final.</p><h3>Frais de collecte et de service</h3><p>Les frais applicables à un lot ou à une collecte sont ceux affichés et acceptés au moment de la demande. Les promotions applicables sont enregistrées dans le dossier de la demande. Une estimation fournie par le vendeur n’est pas une garantie du prix de vente final.</p><h3>Période de vente et articles invendus</h3><p>La période de vente et les choix offerts pour les articles invendus sont régis par les règles affichées dans le compte et peuvent nécessiter une action du vendeur avant une échéance. Aucun transfert bancaire automatique n’est promis tant qu’un mécanisme de paiement vendeur distinct n’a pas été activé.</p><h3>Produit de la vente</h3><p>Après une vente confirmée par le système de paiement, la part du vendeur est calculée à partir du prix de vente réel et du pourcentage de commission verrouillé. Un crédit peut demeurer en attente pendant la vérification du règlement, d’un retour, d’un remboursement ou d’un litige. Un remboursement peut entraîner l’annulation ou l’ajustement du crédit correspondant.</p></section>
    <section lang="en"><h2>English</h2><p>These terms apply when a seller submits items to {siteConfig.businessName} for assessment, listing and sale under the rules displayed in the seller account.</p><h3>Ownership and authenticity</h3><p>The seller confirms that they own the items or are authorized to sell them, that the items are not stolen or counterfeit, and that submitted information is accurate. Prohibited, unsafe or ineligible items may be rejected.</p><h3>Assessment and pricing</h3><p>Items are inspected before publication. Proposed pricing must be approved through the account workflow. The seller commission tier is locked from the initial approved price and does not change solely because an item is later discounted; the dollar payout may still change with the final sale price.</p><h3>Collection and service fees</h3><p>Fees applicable to a batch or pickup are the amounts displayed and accepted when the request is submitted. Applicable promotions are recorded with the request. A seller’s estimated value is not a guarantee of the final selling price.</p><h3>Selling period and unsold items</h3><p>The selling period and available disposition choices for unsold items are governed by the rules displayed in the account and may require seller action before a deadline. No automatic bank payout is promised until a separate seller-payout mechanism has been activated.</p><h3>Sale proceeds</h3><p>After a sale is confirmed by the payment system, the seller share is calculated from the actual selling price and the locked commission percentage. A credit may remain pending while settlement, a return, refund or dispute is reviewed. A refund may reverse or adjust the corresponding seller credit.</p></section>
    <section><h2>Related policies · Politiques connexes</h2><p><Link href="/pickup-policy">Pickup Policy</Link> · <Link href="/privacy">Privacy</Link> · <Link href="/terms">Terms</Link></p></section>
    <Link className="policy-back" href="/"><ArrowLeft/> Back to Rewear</Link>
  </article></main>;
}
