import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { siteConfig } from "@/lib/site-config";

export const metadata: Metadata = { title: "Returns & Refunds | Rewear", description: "Return and refund policy for Rewear purchases." };

export default function ReturnsPage() {
  return <main className="shipping-policy-page"><header className="policy-header"><Link href="/" className="brand">REWEAR<span>.</span></Link><Link href="/account">My account</Link></header><article className="legal-policy">
    <div className="policy-hero"><p className="eyebrow dark">Buyer protection / Protection de l’acheteur</p><h1>Returns & Refunds · Retours et remboursements</h1><p>Effective September 25, 2026 · En vigueur le 25 septembre 2026</p></div>
    <section lang="fr"><h2>Français</h2><p>Les articles vendus sur {siteConfig.businessName} sont principalement d’occasion. Les défauts connus et l’état observé doivent être indiqués dans la fiche de l’article. La présente politique ne limite pas les droits obligatoires prévus par la loi.</p><h3>Article non conforme</h3><p>Si l’article reçu est sensiblement différent de sa description, endommagé pendant le transport ou si un mauvais article a été livré, communiquez avec le soutien dès que raisonnablement possible en conservant l’emballage, les photos et les renseignements de livraison. La demande sera examinée avant toute décision de retour ou de remboursement.</p><h3>Autorisation de retour</h3><p>Ne retournez pas un article sans instructions. Lorsqu’un retour est autorisé, les instructions, le transport applicable et l’adresse de retour sont communiqués dans le dossier de la demande. L’état du bien retourné peut être vérifié à sa réception.</p><h3>Remboursements</h3><p>Un remboursement approuvé doit être effectué par le même fournisseur de paiement lorsque cela est possible. Le statut de la commande et la comptabilité du vendeur doivent être ajustés de façon cohérente avant que le dossier soit considéré comme fermé.</p><h3>Droits légaux</h3><p>Les règles québécoises relatives aux contrats conclus à distance et tout autre droit légal applicable continuent de s’appliquer, notamment lorsque les renseignements obligatoires n’ont pas été fournis ou que le contrat n’a pas été transmis conformément à la loi.</p></section>
    <section lang="en"><h2>English</h2><p>Items sold through {siteConfig.businessName} are primarily second-hand. Known defects and observed condition should be disclosed in the listing. This policy does not limit mandatory rights under applicable law.</p><h3>Item not as described</h3><p>If an item is materially different from its description, damaged in transit or the wrong item was delivered, contact support as soon as reasonably possible and keep the packaging, photos and delivery information. The case will be reviewed before a return or refund decision is made.</p><h3>Return authorization</h3><p>Do not send an item back without instructions. When a return is authorized, the return method, applicable shipping instructions and return destination will be provided in the case. Returned-item condition may be inspected when received.</p><h3>Refunds</h3><p>An approved refund should be processed through the same payment provider where possible. The order state and seller accounting must be reconciled consistently before the case is treated as closed.</p><h3>Legal rights</h3><p>Quebec distance-contract rules and any other applicable statutory rights continue to apply, including rights that may arise when mandatory information was not properly disclosed or a compliant copy of the contract was not delivered.</p></section>
    <section><h2>Support · Soutien</h2><p>{siteConfig.supportEmail ? <a href={`mailto:${siteConfig.supportEmail}`}>{siteConfig.supportEmail}</a> : "Use the signed-in Support chat while payment remains disabled."}</p></section>
    <Link className="policy-back" href="/"><ArrowLeft/> Back to Rewear</Link>
  </article></main>;
}
