"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Bot, Check, FlaskConical, GraduationCap, MessageSquareText, Pencil, ShieldCheck, X } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Mode="chat"|"teach"|"review"|"test";
type Knowledge={id:string;title:string;approved_answer:string;category_code:string|null;tags:string[];status:string;updated_at:string};
type Draft={id:string;draft_type:string;source_kind:string;proposed_title:string|null;proposed_category_code:string|null;proposed_answer:string|null;proposed_rule:Record<string,unknown>|null;conflict_with:string|null;status:string;review_note:string|null;created_at:string};
type Unknown={id:string;customer_question:string;suggested_category_code:string|null;similar_count:number;training_priority:number;status:string;created_at:string};
type Rule={id:string;rule_name:string;instruction:string;priority:number;status:string;updated_at:string};
type Category={code:string;name:string;parent_id:string|null};
type Stats={total:number;waiting:number;human:number;ai:number;urgent:number;resolved:number;unknown_open:number;kb_approved:number;not_helpful:number};
type Permissions={user_id:string;role:string;ai_view:boolean;ai_test:boolean;ai_suggest_training:boolean;ai_edit_training:boolean;ai_approve_training:boolean;ai_manage_behavior_rules:boolean};
type ChatMsg={id:string;kind:"admin"|"ai";body:string;meta?:Record<string,unknown>};

const modeInfo:Record<Mode,{label:string;help:string;icon:typeof Bot}>={
  chat:{label:"Chat",help:"Ask what the bot currently knows and which approved rules it uses.",icon:MessageSquareText},
  teach:{label:"Teach",help:"Describe a change in natural language. It becomes a proposal, never an automatic rule.",icon:GraduationCap},
  review:{label:"Review",help:"Surface unanswered or uncertain customer questions that need admin input.",icon:ShieldCheck},
  test:{label:"Test Bot",help:"Simulate a customer question without affecting a real conversation.",icon:FlaskConical},
};

export function AiTrainerClient({initialKnowledge,initialDrafts,initialUnknown,initialRules,categories,stats,permissions}:{initialKnowledge:Knowledge[];initialDrafts:Draft[];initialUnknown:Unknown[];initialRules:Rule[];categories:Category[];stats:Stats;permissions:Permissions}){
  const supabase=useMemo(()=>createClient(),[]);const router=useRouter();
  const [mode,setMode]=useState<Mode>("chat");const [prompt,setPrompt]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [trainerId,setTrainerId]=useState<string|null>(null);const [messages,setMessages]=useState<ChatMsg[]>([]);const [draft,setDraft]=useState<Draft|null>(null);const [editTitle,setEditTitle]=useState("");const [editAnswer,setEditAnswer]=useState("");const [editCategory,setEditCategory]=useState("");
  const [section,setSection]=useState<"knowledge"|"rules"|"unknown"|"drafts">("knowledge");
  const approvedCategories=categories.filter(c=>c.parent_id!==null);

  async function submit(){if(mode!=="review"&&!prompt.trim())return;setBusy(true);setError(null);const text=prompt.trim();if(text)setMessages(v=>[...v,{id:crypto.randomUUID(),kind:"admin",body:text}]);try{const {data,error:e}=await supabase.functions.invoke("support-trainer",{body:{mode,prompt:text,trainer_conversation_id:trainerId}});if(e)throw new Error(e.message);if(data?.error)throw new Error(data.error);if(data?.trainer_conversation_id)setTrainerId(data.trainer_conversation_id);const reply=String(data?.reply||data?.response||"Done.");setMessages(v=>[...v,{id:crypto.randomUUID(),kind:"ai",body:reply,meta:data}]);if(data?.draft){setDraft(data.draft as Draft);setEditTitle(data.draft.proposed_title||"");setEditAnswer(data.draft.proposed_answer||"");setEditCategory(data.draft.proposed_category_code||"")}setPrompt("")}catch(e){setError(e instanceof Error?e.message:"Trainer request failed")}finally{setBusy(false)}}
  function switchMode(next:Mode){setMode(next);setTrainerId(null);setMessages([]);setDraft(null);setPrompt("");setError(null)}
  async function saveDraft(asDraft:boolean){if(!draft)return;setBusy(true);setError(null);const {error:e}=await supabase.rpc("ai_update_training_draft",{p_draft_id:draft.id,p_title:editTitle,p_answer:editAnswer,p_category_code:editCategory,p_save_as_draft:asDraft});if(e)setError(e.message);else{setDraft({...draft,proposed_title:editTitle,proposed_answer:editAnswer,proposed_category_code:editCategory,status:asDraft?"draft":draft.status});router.refresh()}setBusy(false)}
  async function approveDraft(){if(!draft)return;setBusy(true);setError(null);if(editTitle!==draft.proposed_title||editAnswer!==draft.proposed_answer||editCategory!==draft.proposed_category_code){const {error:e}=await supabase.rpc("ai_update_training_draft",{p_draft_id:draft.id,p_title:editTitle,p_answer:editAnswer,p_category_code:editCategory,p_save_as_draft:false});if(e){setError(e.message);setBusy(false);return}}const {error:e}=await supabase.rpc("ai_approve_training_draft",{p_draft_id:draft.id,p_answer:editAnswer});if(e)setError(e.message);else{setMessages(v=>[...v,{id:crypto.randomUUID(),kind:"ai",body:"Approved. This change is now part of official customer-facing AI knowledge/rules, with version history preserved."}]);setDraft(null);router.refresh()}setBusy(false)}
  async function rejectDraft(ignore=false){if(!draft)return;setBusy(true);const {error:e}=await supabase.rpc("ai_reject_training_draft",{p_draft_id:draft.id,p_ignore:ignore,p_note:null});if(e)setError(e.message);else{setDraft(null);router.refresh()}setBusy(false)}
  async function loadExistingDraft(d:Draft){setMode("teach");setDraft(d);setEditTitle(d.proposed_title||"");setEditAnswer(d.proposed_answer||"");setEditCategory(d.proposed_category_code||"");setMessages([{id:crypto.randomUUID(),kind:"ai",body:"Loaded existing training proposal for review."}])}
  async function archiveKnowledge(id:string){if(!permissions.ai_approve_training)return;setBusy(true);const {error:e}=await supabase.rpc("ai_archive_knowledge",{p_knowledge_id:id});if(e)setError(e.message);else router.refresh();setBusy(false)}

  return <div className="support-trainer-layout">
    <section className="support-panel-card support-trainer-chat">
      <div className="support-mode-tabs">{(Object.keys(modeInfo) as Mode[]).map(m=>{const I=modeInfo[m].icon;return <button key={m} className={mode===m?"active":""} type="button" disabled={m==="test"&&!permissions.ai_test||m==="teach"&&!permissions.ai_suggest_training} onClick={()=>switchMode(m)}><I/> {modeInfo[m].label}</button>})}</div>
      <div style={{padding:"10px 14px",borderBottom:"1px solid #e5e7eb",color:"#64748b",fontSize:12}}>{modeInfo[mode].help}</div>
      <div className="support-trainer-messages">{!messages.length?<div className="support-admin-empty"><Bot/><h3>{modeInfo[mode].label}</h3><p>{modeInfo[mode].help}</p>{mode==="chat"?<p>Try: “What are our current commission rules?”</p>:mode==="teach"?<p>Try: “Payout disputes must always be high priority and go to a human.”</p>:mode==="test"?<p>Try: “I have a $150 jacket. How much will I receive?”</p>:<p>Open the current unanswered-question queue.</p>}</div>:messages.map(m=><div key={m.id} className={`support-trainer-msg ${m.kind}`}><b>{m.kind==="admin"?"You":"AI Trainer"}</b><p>{m.body}</p>{m.meta?.action?<small>Action: {String(m.meta.action)}{m.meta.confidence!==undefined?` · Confidence ${Math.round(Number(m.meta.confidence)*100)}%`:""}{m.meta.source?` · Source: ${String(m.meta.source)}`:""}</small>:null}</div>)}</div>
      {error?<div className="support-admin-error">{error}</div>:null}
      {draft?<div className="support-draft" style={{margin:"0 12px 12px"}}><h4>Proposed Change — NOT ACTIVE YET</h4>{draft.conflict_with?<p><b>Potential conflict/overlap detected.</b> Review existing policy before approval.</p>:null}<label>Title<input className="support-control-input" style={{width:"100%"}} value={editTitle} onChange={e=>setEditTitle(e.target.value)}/></label><label>Category<select className="support-control-select" style={{width:"100%"}} value={editCategory} onChange={e=>setEditCategory(e.target.value)}><option value="">No category</option>{approvedCategories.map(c=><option key={c.code} value={c.code}>{c.code}</option>)}</select></label><label>{draft.draft_type==="behavior"?"Instruction / proposal":"Approved answer preview"}<textarea className="support-note-input" style={{width:"100%",minHeight:100}} value={editAnswer} onChange={e=>setEditAnswer(e.target.value)}/></label><div className="support-button-row" style={{marginTop:9}}>{permissions.ai_approve_training?<button className="support-primary-btn" type="button" disabled={busy||!editAnswer.trim()} onClick={()=>void approveDraft()}><Check/> Approve</button>:null}{permissions.ai_edit_training?<><button className="support-secondary-btn" type="button" disabled={busy} onClick={()=>void saveDraft(true)}><Pencil/> Save as Draft</button><button className="support-danger-btn" type="button" disabled={busy} onClick={()=>void rejectDraft(false)}><X/> Reject</button><button className="support-secondary-btn" type="button" disabled={busy} onClick={()=>void rejectDraft(true)}>Ignore</button></>:null}</div></div>:null}
      <div className="support-trainer-composer"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={mode==="review"?"Review mode can run without a prompt, or ask what needs attention…":"Type a natural-language instruction or question…"} onKeyDown={e=>{if(e.key==="Enter"&&(e.metaKey||e.ctrlKey))void submit()}}/><div className="support-reply-actions"><span>Ctrl/⌘ + Enter to send · Official changes always require approval</span><button className="support-primary-btn" type="button" disabled={busy||(mode!=="review"&&!prompt.trim())} onClick={()=>void submit()}>{busy?"Working…":"Send"}</button></div></div>
    </section>

    <aside className="support-side">
      <section className="support-panel-card"><h3>AI performance</h3><div className="support-metric-grid"><div><b>{stats.ai}</b><span>AI handling now</span></div><div><b>{stats.waiting}</b><span>Waiting for human</span></div><div><b>{stats.unknown_open}</b><span>Unanswered</span></div><div><b>{stats.kb_approved}</b><span>Approved knowledge</span></div><div><b>{stats.not_helpful}</b><span>Not Helpful</span></div><div><b>{stats.urgent}</b><span>Urgent open</span></div></div></section>
      <section className="support-panel-card"><div className="support-filter-tabs">{(["knowledge","rules","unknown","drafts"] as const).map(s=><button key={s} type="button" className={section===s?"active":""} onClick={()=>setSection(s)}>{s==="knowledge"?"Knowledge":s==="rules"?"Behavior Rules":s==="unknown"?"Unanswered":"Pending"}</button>)}</div>
        {section==="knowledge"?<div className="support-kb-list">{initialKnowledge.map(k=><div className="support-kb-item" key={k.id}><b>{k.title}</b><p>{k.category_code||"Uncategorized"} · {k.status}</p><p>{k.approved_answer.slice(0,220)}{k.approved_answer.length>220?"…":""}</p>{k.status==="approved"&&permissions.ai_approve_training?<button className="support-danger-btn" type="button" onClick={()=>void archiveKnowledge(k.id)}>Archive</button>:null}</div>)}</div>:null}
        {section==="rules"?<div className="support-kb-list">{initialRules.map(r=><div className="support-kb-item" key={r.id}><b>{r.rule_name}</b><p>Priority {r.priority} · {r.status}</p><p>{r.instruction}</p></div>)}</div>:null}
        {section==="unknown"?<div className="support-kb-list">{initialUnknown.length?initialUnknown.map(u=><div className="support-kb-item" key={u.id}><b>{u.customer_question}</b><p>Similar questions: {u.similar_count} · Training priority: {u.training_priority}</p><button className="support-secondary-btn" type="button" onClick={()=>{switchMode("teach");setPrompt(`Create an approved support answer for this unanswered customer question: ${u.customer_question}`)}}>Teach this answer</button></div>):<p>No unanswered questions.</p>}</div>:null}
        {section==="drafts"?<div className="support-kb-list">{initialDrafts.length?initialDrafts.map(d=><button key={d.id} type="button" className="support-kb-item" style={{textAlign:"left",background:"white"}} onClick={()=>void loadExistingDraft(d)}><b>{d.proposed_title||"Training proposal"}</b><p>{d.draft_type} · {d.status} · {d.source_kind}</p>{d.conflict_with?<p>⚠ Conflict/overlap flagged</p>:null}</button>):<p>No pending drafts.</p>}</div>:null}
      </section>
    </aside>
  </div>
}
