import Link from "next/link";
import { redirect } from "next/navigation";
import { requireAdmin } from "@/lib/admin-auth";
import { postalReadiness } from "@/lib/postal-server";
import { BAND_NAMES,weightBand } from "@/lib/postal";
import { savePostalConfig,savePostalParcel } from "./actions";
import "../items/items.css";
import "./postal-admin.css";
export const dynamic="force-dynamic";
type ParcelRecord={weight_grams:number;length_mm:number;width_mm:number;height_mm:number;manual_review:boolean;local_only:boolean;mailing_tube:boolean;unpackaged:boolean};
type State={config:{enabled:boolean;origin_postal:string;band_limits:number[];revision:number};items:{id:string;name:string;category:string;status:string;parcel:ParcelRecord|null}[]};
export default async function PostalAdmin({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}) {
 const {supabase,access}=await requireAdmin();if(!access.can_manage_shipping)redirect("/admin");if(!access.has_aal2)redirect("/admin/mfa");
 const {data,error}=await supabase.rpc("admin_postal_state");if(error)throw new Error("Shipping configuration could not be loaded");
 const state=data as State;const params=await searchParams;const current=state.items.find(i=>i.id===params.item);const p=current?.parcel;
 const ready=postalReadiness();
 return <main className="section-wrap postal-admin"><header className="admin-items-top"><Link href="/admin" className="brand">REWEAR<span>.</span></Link><nav><Link href="/admin/items">Items</Link><Link href="/admin/operations">Local delivery policy</Link></nav></header><section className="admin-items-wrap"><h1>Postal shipping</h1><p>Canada Post rates for Canadian destinations outside the local delivery service. Configure verified packed parcels; prices come from the carrier, not from weight-band estimates.</p>
 {typeof params.message==="string"?<p role="status" className="admin-items-message">{params.message}</p>:null}
 <section className="admin-items-card"><h2>Connection readiness</h2><ul><li>Carrier credentials: {ready.carrier?"Present":"Missing"}</li><li>Production app confirmed: {ready.production?"Yes":"No"}</li><li>Secure quote storage credentials: {ready.storage?"Present":"Missing"}</li><li>Customer quotes: {state.config.enabled?"Enabled":"Paused"}</li></ul><p>Credential presence does not verify the connection. Run a real quote after configuration. Keep API secrets in server environment variables; never enter them in a chat or public form.</p><details><summary>Required server configuration</summary><p>CANADA_POST_CLIENT_ID, CANADA_POST_CLIENT_SECRET, CANADA_POST_MODE=production, and SUPABASE_SECRET_KEY (or the existing SUPABASE_SERVICE_ROLE_KEY). Optional: CANADA_POST_CUSTOMER_NUMBER and CANADA_POST_CONTRACT_ID for eligible account rates. Use a production app with access to Rating API. Test-app prices must not be shown to buyers.</p></details></section>
 <section className="admin-items-card"><h2>Four weight bands</h2><p>Each limit is inclusive; the next band starts above the previous limit. These labels organize real packed weights and never replace dimensional rating.</p><form action={savePostalConfig} className="admin-item-form"><label>Warehouse origin postal code<input name="origin" defaultValue={state.config.origin_postal} maxLength={7} placeholder="Enter verified warehouse postal code"/></label><div className="postal-admin-grid">{state.config.band_limits.map((limit,i)=><label key={i}>{i+1}. {BAND_NAMES[i]} — maximum grams<input type="number" name={`band_${i+1}`} defaultValue={limit} min={1} max={30000} step={1} required/></label>)}</div><label><input type="checkbox" name="enabled" defaultChecked={state.config.enabled}/> Enable live production quotes</label><button>Save settings</button></form></section>
 <section className="admin-items-card"><h2>Verified parcel measurements</h2><p>One item or listing bundle = one separately packed parcel. Measure the outside of the final packaging and include all packing materials in its weight. No automatic consolidation or guessed category weights.</p><form method="get"><label>Inventory item<select name="item" defaultValue={current?.id??""} required><option value="">Choose an item</option>{state.items.map(i=><option key={i.id} value={i.id}>{i.name} · {i.category} · {i.parcel?"Measured":"Needs measurements / Home inspection"}</option>)}</select></label><button>Open parcel</button></form>
 {current?<form action={savePostalParcel} className="admin-item-form"><h3>{current.name}</h3><input type="hidden" name="item" value={current.id}/><div className="postal-admin-grid">{[["weight","Packed weight (grams)",p?.weight_grams,100000],["length","Packed length (mm)",p?.length_mm,10000],["width","Packed width (mm)",p?.width_mm,10000],["height","Packed height (mm)",p?.height_mm,10000]].map(([key,label,value,max])=><label key={String(key)}>{label}<input name={String(key)} type="number" min={1} max={Number(max)} step={1} defaultValue={value??""} required/></label>)}</div><label><input name="manual" type="checkbox" defaultChecked={p?.manual_review??true}/> Manual shipping review required</label><label><input name="local" type="checkbox" defaultChecked={p?.local_only}/> Local delivery only</label><label><input name="tube" type="checkbox" defaultChecked={p?.mailing_tube}/> Mailing tube</label><label><input name="unpackaged" type="checkbox" defaultChecked={p?.unpackaged}/> Unpackaged / irregular parcel</label>{p?<p>Weight band: {weightBand(p.weight_grams,state.config.band_limits)??"Outside automatic limits"}</p>:null}<p>Home & Decor restrictions still apply even when a parcel override is saved. Review its inspection before clearing restrictions.</p><button>Save verified parcel</button></form>:null}
 </section><section className="admin-items-card"><h2>Safety and fulfilment</h2><p>Quotes expire after 10 minutes. Changing the destination, weight, dimensions or configuration invalidates existing quotes at checkout. Items over the supported limits require manual review. This integration does not purchase labels, charge buyers or activate payouts.</p></section></section></main>;
}
